<?xml version="1.0" ?>

<robot name="$(arg roboname)" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:arg name="camera_left" default="false"/>
  <xacro:arg name="camera_right" default="false"/>
  <xacro:arg name="velodyne_points" default="false"/>
  <xacro:arg name="front_laser_points" default="false"/>


  <xacro:property name="PI" value="3.1415926835897931"/>
<!--  <xacro:property name="base_height" value="0"/> -->
  <xacro:property name="base_height" value="0.465"/>
  <xacro:property name="base_mass" value="210"/>
  <xacro:property name="base_mass_ixx" value="19"/>
  <xacro:property name="base_mass_iyy" value="49"/>
  <xacro:property name="base_mass_izz" value="49"/>
  <xacro:property name="base_mass_ixz" value="0"/>
  <xacro:property name="tyre_x" value="0.75"/>
  <xacro:property name="tyre_y" value="0.42"/>
  <xacro:property name="tyre_length" value="0.12"/>
  <xacro:property name="tyre_r" value="0.2"/>
  <xacro:property name="tyre_radius" value="0.2"/>
  <xacro:property name="tyre_mass" value="5"/>
  <xacro:property name="tyre_mass_ixx" value="0.1"/>
  <xacro:property name="tyre_mass_iyy" value="0.05"/>
  <xacro:property name="tyre_mass_izz" value="0.05"/>
  <xacro:property name="car_height" value="0.75"/>
  <xacro:property name="car_to_bumper" value="2.4"/>
  <xacro:property name="front_bumper_height" value="${car_height/2}"/>
  <xacro:property name="sensor_box" value="0.25"/>
  <xacro:property name="sensor_box2" value="0.31"/>
  <xacro:property name="camera_box" value="0.1"/>
  <!-- <xacro:property name="tyre_height" value="-0.696"/> -->
  <xacro:property name="str_length" value="0.01"/>
  <xacro:property name="str_radius" value="0.1"/>
  <xacro:property name="str_angle" value="0.4"/>
  <xacro:property name="car_width" value="0.72"/>
  <xacro:property name="front_laser_points" value="$(arg front_laser_points)"/>
  <xacro:property name="velodyne_points" value="$(arg velodyne_points)"/>
  <xacro:property name="camera_right" value="$(arg camera_right)"/>
  <xacro:property name="camera_left" value="$(arg camera_left)"/>
  <xacro:property name="tyre_origin">
	<origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
    </xacro:property>
    <xacro:property name="tyre_origin_2">
          <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
    </xacro:property>
    <xacro:property name="tyre_origin_3">
          <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
  </xacro:property>

	<xacro:include filename="$(find system_resources)/urdf/catvehicle.gazebo"/>
    <xacro:if value="${front_laser_points}">
    	<xacro:include filename="$(find system_resources)/urdf/catvehicle_front_laser_points.gazebo"/>
    </xacro:if>
    <xacro:if value="${velodyne_points}">
      <!-- You can pass parameters in order to change the max/min
           horizontal angles of the velodyne sensors. These are interpreted
           in the velodyne_points gazebo file -->
      <xacro:arg name="velodyne_min_angle" default="-0.4"/>
      <xacro:arg name="velodyne_max_angle" default="0.4"/>
      <xacro:property name="velodyne_min_angle" value="$(arg velodyne_min_angle)"/>
      <xacro:property name="velodyne_max_angle" value="$(arg velodyne_max_angle)"/>

    	<xacro:include filename="$(find system_resources)/urdf/catvehicle_velodyne_points.gazebo"/>
    </xacro:if>
    <xacro:if value="${camera_right}">
    	<xacro:include filename="$(find system_resources)/urdf/catvehicle_right_camera.gazebo"/>
    </xacro:if>
    <xacro:if value="${camera_left}">
    	<xacro:include filename="$(find system_resources)/urdf/catvehicle_left_camera.gazebo"/>
    </xacro:if>

  <xacro:arg name="camera_name"   default="zed" />
  <xacro:arg name="camera_model"  default="zed" />
  <xacro:arg name="base_frame"    default="base_link" />
  <xacro:arg name="cam_pos_x"     default="0.15" />
  <xacro:arg name="cam_pos_y"     default="0.0" />
  <xacro:arg name="cam_pos_z"     default="1.6" />
  <xacro:arg name="cam_roll"      default="0.0" />
  <xacro:arg name="cam_pitch"     default="0.0" />
  <xacro:arg name="cam_yaw"       default="0.0" />

  <xacro:include filename="$(find system_resources)/urdf/zed_macro.urdf.xacro" />
  <xacro:zed_camera name="$(arg camera_name)" model="$(arg camera_model)" parent="$(arg base_frame)">
    <origin xyz="$(arg cam_pos_x) $(arg cam_pos_y) $(arg cam_pos_z)" rpy="$(arg cam_roll) $(arg cam_pitch) $(arg cam_yaw)" />
  </xacro:zed_camera>


<!--Car Body-->





<link name="base_link">
    <collision>
         <origin xyz="0 0 ${base_height}" rpy="0 0 0"/>
           <geometry>
            <box size="1.5 ${car_width} ${car_height}"/>
        </geometry>
      </collision>
     <visual>
        <origin xyz="0 0 ${base_height}" rpy="0 0 0"/>
        <geometry>
          <box size="1.5 ${car_width} ${car_height}"/>
        </geometry>
     </visual>
</link>

<joint name="inertial_joint" type="fixed">
      <parent link="base_link"/>
      <child link="main_mass"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
</joint>

<link name="main_mass" type="fixed">
     <parent link="inertial_joint"/>
     <inertial>
        <origin xyz="0 0 ${base_height}" rpy="0 0 0"/>
        <mass value="${base_mass}"/>
        <inertia
          ixx="${base_mass_ixx}"  ixy="0.000000" ixz="${base_mass_ixz}"
          iyy="${base_mass_iyy}" iyz="0.000000"
          izz="${base_mass_izz}"/>
      </inertial>
</link>

<!--Back Right Wheel-->




<joint name="back_right_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="back_right_wheel_link"/>
      <origin xyz="${-tyre_x} ${-tyre_y} ${tyre_r}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.1"/>
     <limit effort="10000" velocity="100" />
      <joint_properties damping="0.0" friction="0.0" />
</joint>

<link name="back_right_wheel_link">
     <collision>
      <xacro:insert_block name="tyre_origin"/>
        <geometry>
         <cylinder length="${tyre_length}" radius="${tyre_radius}"/>
        </geometry>
     </collision>

     <visual>
      <xacro:insert_block name="tyre_origin_3"/>
        <geometry>
          <cylinder length="${tyre_length}" radius="${tyre_radius}"/>
      <scale xyz="1.2 1 1"/>
        </geometry>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${tyre_mass}"/>
        <inertia
          ixx="${tyre_mass_ixx}"  ixy="0.000000"  ixz="0.000000"
          iyy="${tyre_mass_iyy}"  iyz="0.000000"
          izz="${tyre_mass_izz}"/>
      </inertial>
</link>




<!--Back Left Wheel-->




<joint name="back_left_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="back_left_wheel_link"/>
      <origin xyz="${-tyre_x} ${tyre_y} ${tyre_r}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.1"/>
      <limit effort="10000" velocity="100" />
      <joint_properties damping="0.0" friction="0.0" />
</joint>

<link name="back_left_wheel_link">
     <collision>
      <xacro:insert_block name="tyre_origin"/>
        <geometry>
         <cylinder length="${tyre_length}" radius="${tyre_radius}"/>
        </geometry>
     </collision>

     <visual>
      <xacro:insert_block name="tyre_origin_2"/>
        <geometry>
          <cylinder length="${tyre_length}" radius="${tyre_radius}"/>
          <scale xyz="1.2 1 1"/>
        </geometry>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${tyre_mass}"/>
        <inertia
          ixx="${tyre_mass_ixx}"  ixy="0.000000"  ixz="0.000000"
          iyy="${tyre_mass_iyy}"  iyz="0.000000"
          izz="${tyre_mass_izz}"/>
      </inertial>
</link>



<!--Right Steering-->




<joint name="front_right_steering_joint" type="revolute">
	<parent link="base_link"/>
	<child link="front_right_steering_link"/>
	<origin xyz="${tyre_x} ${-car_width/2 - str_length/2} ${tyre_r}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
	<limit effort="1000.0" lower="${-str_angle}" upper="${str_angle}" velocity="0.5"/>
</joint>

<link name="front_right_steering_link">
	<collision>
	      <xacro:insert_block name="tyre_origin"/>
	        <geometry>
        	 <cylinder length="${str_length}" radius="${str_radius}"/>
       		</geometry>
	</collision>

	<visual>
              <xacro:insert_block name="tyre_origin"/>
                <geometry>
                 <cylinder length="${str_length}" radius="${str_radius}"/>
                </geometry>
	</visual>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="5.00"/>
        <inertia
          ixx="0.1"  ixy="0.000000"  ixz="0.000000"
          iyy="0.05"  iyz="0.000000"
          izz="0.05"/>
      </inertial>
</link>



<!--Right Front Wheel-->




<joint name="front_right_wheel_joint" type="continuous">
      <parent link="front_right_steering_link"/>
      <child link="front_right_wheel_link"/>
      <origin xyz="0 ${-str_length/2 - tyre_length/2} 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
</joint>

<link name="front_right_wheel_link">
     <collision>
      <xacro:insert_block name="tyre_origin"/>
        <geometry>
         <cylinder length="${tyre_length}" radius="${tyre_radius}"/>
	</geometry>
     </collision>

     <visual>
      <xacro:insert_block name="tyre_origin_3"/>
        <geometry>
          <cylinder length="${tyre_length}" radius="${tyre_radius}"/>
        <scale xyz="1.2 1 1"/>
       </geometry>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${tyre_mass}"/>
        <inertia
          ixx="${tyre_mass_ixx}"  ixy="0.000000"  ixz="0.000000"
          iyy="${tyre_mass_iyy}"  iyz="0.000000"
          izz="${tyre_mass_izz}"/>
      </inertial>
</link>


<!--Left Steering-->



<joint name="front_left_steering_joint" type="revolute">
        <parent link="base_link"/>
        <child link="front_left_steering_link"/>
        <origin xyz="${tyre_x} ${car_width/2 + str_length/2} ${tyre_r}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit effort="1000.0" lower="${-str_angle}" upper="${str_angle}" velocity="0.5"/>
</joint>

<link name="front_left_steering_link">
      <parent link="base_link"/>
        <collision>
              <xacro:insert_block name="tyre_origin"/>
                <geometry>
                 <cylinder length="${str_length}" radius="${str_radius}"/>
                </geometry>
        </collision>

        <visual>
              <xacro:insert_block name="tyre_origin"/>
                <geometry>
                 <cylinder length="${str_length}" radius="${str_radius}"/>
                </geometry>
        </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="5.00"/>
        <inertia
          ixx="0.1"  ixy="0.000000"  ixz="0.000000"
          iyy="0.05"  iyz="0.000000"
          izz="0.05"/>
      </inertial>
</link>



<!--Front left Wheel-->



<joint name="front_left_wheel_joint" type="continuous">
      <parent link="front_left_steering_link"/>
      <child link="front_left_wheel_link"/>
      <origin xyz="0 ${str_length/2 + tyre_length/2} 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>

      <dynamics damping="0.1"/>
      <limit effort="10000" velocity="100" />
      <joint_properties damping="0.0" friction="0.0" />

</joint>


<link name="front_left_wheel_link">
     <parent link="front_left_wheel_joint"/>
     <collision>
	<origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
         <cylinder length="${tyre_length}" radius="${tyre_radius}"/>
        </geometry>
     </collision>

     <visual>
      <xacro:insert_block name="tyre_origin_2"/>
       <geometry>
          <cylinder length="${tyre_length}" radius="${tyre_radius}"/>
            <scale xyz="1.2 1 1"/>
       </geometry>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${tyre_mass}"/>
        <inertia
          ixx="${tyre_mass_ixx}"  ixy="0.000000"  ixz="0.000000"
          iyy="${tyre_mass_iyy}"  iyz="0.000000"
          izz="${tyre_mass_izz}"/>
      </inertial>
</link>

<!-- Cameras-->

<joint name="camera_right_joint" type="fixed">
<origin xyz="-0.75 -${car_width/2} ${0.725 + camera_box/2 + 0.85}" rpy="0 0 -${PI/2}"/>
	<axis xyz="0 0 1"/>
	<parent link="base_link"/>
	<child link="camera_right_link"/>
</joint>

<link name="camera_right_link">
	<collision>
	  <origin xyz="0 0 0" rpy="0 0 0"/>
	  <geometry>
	   <box size="${camera_box} ${camera_box} ${camera_box}"/>
	  </geometry>
	</collision>

	<visual>
	  <origin xyz="0 0 0" rpy="0 0 0"/>
	  <geometry>
	  <box size="${camera_box} ${camera_box} ${camera_box}"
/>
          </geometry>
	</visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
</link>

<joint name="camera_left_joint" type="fixed">
<origin xyz="-0.75 ${car_width/2} ${0.725 + camera_box/2 + 0.85}" rpy="0 0 ${PI/2}"/>
	<axis xyz="0 0 1"/>
	<parent link="base_link"/>
	<child link="camera_left_link"/>
</joint>

<link name="camera_left_link">
	<collision>
	  <origin xyz="0 0 0" rpy="0 0 0"/>
	  <geometry>
	   <box size="${camera_box} ${camera_box} ${camera_box}"/>
	  </geometry>
	</collision>

	<visual>
	  <origin xyz="0 0 0" rpy="0 0 0"/>
	  <geometry>
	  <box size="${camera_box} ${camera_box} ${camera_box}"
/>
          </geometry>
	</visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
</link>


<joint name="camera_joint" type="fixed">
<origin xyz="0 0 ${0.725 + sensor_box/2 + 0.85}" rpy="0 0 0"/>
	<axis xyz="0 0 1"/>
	<parent link="base_link"/>
	<child link="camera_link"/>
</joint>

<link name="camera_link">
	<collision>
	  <origin xyz="0 0 0" rpy="0 0 0"/>
	  <geometry>
	   <box size="${sensor_box} ${sensor_box} ${sensor_box}"/>
	  </geometry>
	</collision>

	<visual>
	  <origin xyz="0 0 0" rpy="0 0 0"/>
	  <geometry>
	  <box size="${sensor_box} ${sensor_box} ${sensor_box}"
/>
          </geometry>
	</visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
</link>



<!--Velodyne LIDAR-->

<joint name="velodyne_joint" type="fixed">
	<origin xyz="0 0 ${sensor_box/2 + 0.01}" rpy="0 0 0"/>
	<axis xyz="0 0 1"/>
	<parent link="camera_link"/>
	<child link="velodyne_link"/>
</joint>

<link name="velodyne_link">
        <collision>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
           <box size="${sensor_box} ${sensor_box} ${sensor_box}"/>
          </geometry>
        </collision>

        <visual>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
           <box size="${sensor_box} ${sensor_box} ${sensor_box}"/>
          </geometry>
        </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
</link>

<joint name="front_laser_joint" type="fixed">
	<origin xyz="${car_to_bumper} 0 ${front_bumper_height + sensor_box/2 + 0.01}" rpy="0 0 0"/>
	<axis xyz="0 0 1"/>
	<parent link="base_link"/>
	<child link="front_laser_link"/>
</joint>

<link name="front_laser_link">
     <parent link="front_laser_joint"/>
        <collision>
          <origin xyz="0 0 0" rpy="0 0.0 0"/>
          <geometry>
           <box size="${sensor_box} ${sensor_box} ${sensor_box}"/>
          </geometry>
        </collision>

        <visual>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
           <box size="${sensor_box} ${sensor_box} ${sensor_box}"/>
          </geometry>
        </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
</link>

<!-- motors and transmissions for the two rear wheels -->
  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="back_right_wheel_joint">
      <hardwareInterface>VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="back_left_wheel_joint">
      <hardwareInterface>VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="rack_and_pinion_left">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="front_left_steering_joint">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="eps_left">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="rack_and_pinion_right">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="front_right_steering_joint">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="eps_right">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

</robot>
